# Generated by Django 5.0.6 on 2024-07-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='population',
        ),
        migrations.AddField(
            model_name='city',
            name='is_state_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='state',
            name='is_state_available',
            field=models.BooleanField(default=True),
        ),
    ]
